## Filebeat configuration
## https://github.com/elastic/beats/blob/master/deploy/docker/filebeat.docker.yml
#

filebeat.inputs:
  - type: log
    paths:
      - '/tmp/mysql-docker.log'
    multiline:
      pattern: '^.*?\[.*?      \|.*?\[.*? \b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}'
      match: after
      negate: true


filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: elastic
  password: 'changeme'
  index: "mysql-logs"
  pipeline: "mysql-logs-pipeline"
  space.id: "mysql-logs"

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0

setup:
  template.enabled: false
  ilm.enabled: false